#### **NumPy Basics for Data Science: A Beginner-Friendly Guide**

# Why NumPy is Needed When We Have Python Lists ?

- Speed
- Element-wise operations
- Broadcasting

### Explanation
Python lists are versatile and easy to use, but they are not efficient for numerical computations. NumPy arrays offer speed, memory efficiency, and functionality tailored for numerical and data science tasks.

### Example: Comparing Python Lists and NumPy Arrays

In [ ]:
import numpy as np
import time

In [ ]:
# Create two small lists and two small NumPy arrays
python_list1 = [i for i in range(1000000)]
python_list2 = [i for i in range(1000000)]

In [ ]:
numpy_array1 = np.array(python_list1)
numpy_array2 = np.array(python_list2)

In [ ]:
# Adding Python lists
start_time = time.time()
python_sum = [python_list1[i] + python_list2[i] for i in range(len(python_list1))]
end_time = time.time()
python_time = end_time - start_time
print("Time taken using Python list:", python_time, "seconds")

Time taken using Python list: 0.1146860122680664 seconds


In [ ]:
# Adding NumPy arrays
start_time = time.time()
numpy_sum = numpy_array1 + numpy_array2
end_time = time.time()
numpy_time = end_time - start_time
print("Time taken using NumPy array:", numpy_time, "seconds")

Time taken using NumPy array: 0.010779619216918945 seconds


In [ ]:
# Comparing speed
speedup = python_time / numpy_time
print(f"NumPy is approximately {speedup:.2f} times faster than Python lists for this operation.")

NumPy is approximately 10.64 times faster than Python lists for this operation.


---

# Creating numpy arrays

### 0D Array (Scalar)

In [ ]:
scalar = np.array(42)
print("0D Array (Scalar):", scalar)
print("Shape:", scalar.shape)

0D Array (Scalar): 42
Shape: ()


### 1D Array

In [ ]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)
print("Shape:", array_1d.shape)

1D Array: [1 2 3 4 5]
Shape: (5,)


### 2D Array

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


### 3D Array

In [ ]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


### Can We Create 4D or Higher Dimensions?

Yes! NumPy supports arrays with more than 3 dimensions.

###  4D array

In [ ]:
array_4d = np.random.rand(2, 2, 2, 2)
print("4D Array:")
print(array_4d)
print("Shape:", array_4d.shape)

4D Array:
[[[[0.05691064 0.90429059]
   [0.84799349 0.56583088]]

  [[0.96285618 0.95329585]
   [0.34951847 0.60783686]]]


 [[[0.7538548  0.99768314]
   [0.32736809 0.09041516]]

  [[0.29343473 0.92258336]
   [0.1672475  0.06774574]]]]
Shape: (2, 2, 2, 2)


---

# Different Ways to Create Arrays

### Using `np.array()`

In [ ]:
array_from_list = np.array([1, 2, 3, 4])
print("Array from list:", array_from_list)

Array from list: [1 2 3 4]


### Using `np.zeros()`

In [ ]:
zeros_array = np.zeros((2, 3))
print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


### Using `np.ones()`

In [ ]:
ones_array = np.ones((2, 3))
print("Array of ones:")
print(ones_array)

Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]


### Using `np.arange()`

lower bound inclusive, upper bound exclusive

In [ ]:
arange_array = np.arange(1, 10, 2)
print("Array using np.arange():", arange_array)

Array using np.arange(): [1 3 5 7 9]


### Using `np.linspace()`

both ends inclusive , unless added endpoint=False parameter

In [ ]:
linspace_array = np.linspace(0, 1, 5,endpoint=False)
print("Array using np.linspace():", linspace_array)

Array using np.linspace(): [0.  0.2 0.4 0.6 0.8]


How is `arange` and `linspace` different ?

- `arange` generates values from 1 to 10 with a step of 2
- `linspace` generates 5 values from 1 to 10 (inclusive)

### Using `np.random` Module

lower bound inclusive, upper bound exclusive

In [ ]:
random_integers = np.random.randint(1, 10, size=(2, 3))
print("Random integers array:")
print(random_integers)

Random integers array:
[[4 7 5]
 [8 2 2]]


---

# Additional Topics for Starting ML with NumPy

### Array Indexing and Slicing

#### 1D Array Slicing

In [ ]:
array = np.array([10, 20, 30, 40, 50])
print("Original Array:", array)
print("Element at index 2:", array[2])
print("Slice (index 1 to 3):", array[1:4])

Original Array: [10 20 30 40 50]
Element at index 2: 30
Slice (index 1 to 3): [20 30 40]


#### 2D Array Slicing

slicing of rows and columns separated by comma

In [ ]:
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Original 2D Array:")
print(array_2d)
print()
print("Slice row 1:", array_2d[1, :])  # Entire second row
print()
print("Slice column 2:", array_2d[:, 2])  # Entire third column
print()
print("Slice subarray (rows 0-1, cols 1-2):")
print(array_2d[0:2, 1:3])

Original 2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Slice row 1: [40 50 60]

Slice column 2: [30 60 90]

Slice subarray (rows 0-1, cols 1-2):
[[20 30]
 [50 60]]


---

### Array Operations

In [ ]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print("Addition:", array1 + array2)
print("Multiplication:", array1 * array2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]


---

### Broadcasting

#### Where Broadcasting Works

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Array:")
print(array)
print("After adding scalar 10:")
print(array + 10)  # Broadcasting works here

Original Array:
[[1 2 3]
 [4 5 6]]
After adding scalar 10:
[[11 12 13]
 [14 15 16]]


#### Where Broadcasting Fails

In [ ]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 2])  # Mismatched dimensions
try:
    print("Attempting to add arrays with mismatched dimensions:")
    print(array1 + array2)
except ValueError as e:
    print("Error:", e)

Attempting to add arrays with mismatched dimensions:
Error: operands could not be broadcast together with shapes (2,3) (2,) 


---

### Matrix Multiplication

In [ ]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Matrix Multiplication:")
print(np.dot(matrix1, matrix2))

Matrix Multiplication:
[[19 22]
 [43 50]]


In [ ]:
matrix1@matrix2

array([[19, 22],
       [43, 50]])

---

### Aggregations

In [ ]:
array = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Max:", np.max(array))

Sum: 15
Mean: 3.0
Max: 5
